### ISSUE TITLE
System unavailable . Please try again

### ISSUE THREAD

**Issue by sarishti** [paypal/sdk-packages#102]
I am using adaptive payment with one primary and 1 secondary receiver using MPL 2-1-7 Demo. After click on pay with paypal button, getting login screen and after login during payment I am getting error "System unavailable . Please try again"

**Comment by bluk** [comment]
Thanks for the report. I've opened internal issue PPPLMER-25614 to track down the "System is unavailable. Please try again later." alert in the sandbox environment. It would be helpful if you can also detail more about your environment (iOS/Android, whether you are seeing this issue in sandbox or live/production) to ensure that this is the same issue as #98. Thanks.

**Comment by sarishti** [comment]
Thanks for reply. I am using iOS(9.3) sandbox environment .Please let me know if you require any further detail.I will be appreciate if you provide solution as soon as possible.

**Comment by bluk** [comment]
The `System is unavailable. Please try again later.` should be resolved. If you still encounter the issue, please leave a comment. Thanks for your patience.

**Comment by ganeshank** [comment]
I am getting the same error for sandbox environment, Please help me ASAP

**Comment by xiaoleih41** [comment]
If you haven't been approved for live production on this product, please consider to look into other newer Braintree/PayPal product as this product is deprecated and no more new integration will be approved.
