### ISSUE TITLE
"Your account is restricted or locked. Go to www.paypal.com to resolve this issue."

### ISSUE THREAD

**Issue by meet2011** [paypal/sdk-packages#103]
We are using adaptive payment method for android under sandbox enviorment and its working well but when we switched to live environment its throwing error. Let us know if you required further information to investigate the issue.

**Account Account not found. Unilateral receiver not allowed in chained payment is restricted**

**Comment by bluk** [comment]
Please open a ticket with [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) to resolve this issue. Note that the API is under limited release so your account must be approved.
