### ISSUE TITLE
Bitcode not Enabled

### ISSUE THREAD

**Issue by kuldeep13990** [paypal/sdk-packages#107]
When i try to build my project it display below error of bitcode.

**libPayPalMPL.a(PayPal.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64**

I set EnableBitcode to NO but it will show me another too much error.

so please update this with Bitcode Enable.

**Comment by pp-randy** [comment]
Do you have a particular type of payment requiring the MPL that isn't supported by https://github.com/paypal/PayPal-iOS-SDK?

**Comment by kuldeep13990** [comment]
in above SDK, all the payment should go to one person and i son't want to do that.

i want to share payment fifty fifty between 2 person and that can't be done in above SDK which you mentioned.

**Comment by kuldeep13990** [comment]
@pp-randy , I noticed that this MPL is working with .xcodeproj

**Comment by pp-randy** [comment]
Does the MPL work for you then as an .xcodeproj since you are able to open it?

**Comment by kuldeep13990** [comment]
@pp-randy ,ni can build project successfully but when i implement some methods of paypal it will showing lots of error.

**Comment by kuldeep13990** [comment]
@pp-randy , how can i implement mil with no error? it's urgent.

**Comment by pp-randy** [comment]
What are the errors you are seeing with bitcode disabled?

**Comment by kuldeep13990** [comment]
@pp-randy  i upload screenshots

![screen shot 2017-04-07 at 10 22 08 am](https://cloud.githubusercontent.com/assets/5965337/24786107/8062bda2-1b7c-11e7-833f-a7f5151d1409.png)
![screen shot 2017-04-07 at 10 22 25 am](https://cloud.githubusercontent.com/assets/5965337/24786112/80c5cbd6-1b7c-11e7-8359-94666eb512ab.png)
![screen shot 2017-04-07 at 10 22 38 am](https://cloud.githubusercontent.com/assets/5965337/24786111/80c2f12c-1b7c-11e7-817e-e3737e869245.png)
![screen shot 2017-04-07 at 10 22 49 am](https://cloud.githubusercontent.com/assets/5965337/24786110/80c0b754-1b7c-11e7-8a7d-8d56e84fe04a.png)

**Comment by pp-randy** [comment]
I will see if someone is familiar with this error; however, this seems like it is related to compiling with 64-bit. 

I found a video on YouTube that might help with this, will you let me know if it helps?
https://youtu.be/d-pJLRy4rVk

**Comment by bluk** [comment]
For the linker errors above, are you linking with `libxml2`? In the `Other Linker Flags`, you need a `-lxml2`.

![screen shot 2017-04-07 at 3 29 55 pm](https://cloud.githubusercontent.com/assets/94150/24819869/0a7b971e-1bac-11e7-839f-4914b49f6a4d.png)

**Comment by kuldeep13990** [comment]
@bluk  thanks man, your suggestion clear all the errors.
