### ISSUE TITLE
Pay With Paypal Button not Showing

### ISSUE THREAD

**Issue by kuldeep13990** [paypal/sdk-packages#108]
i try to add "Pay with PayPal" button to my View at Specific Position with below code.

```
UIButton *button = [[PayPal getPayPalInst] getPayButtonWithTarget:self andAction:@selector(payWithPayPal) andButtonType:BUTTON_294x43 andButtonText:BUTTON_TEXT_PAY];
    
    button.frame = CGRectMake(0, 0, payPalBackVW.frame.size.width, payPalBackVW.frame.size.height);
    [payPalBackVW addSubview:button];
```

but every time button is nil.
can you help me what is the issue?

**Comment by bluk** [comment]
Did you implement all of the delegate methods that are specified as required in the documentation?

* `paymentFailedWithCorrelationID:`
* `paymentSuccessWithKey:andStatus:`
* `paymentCanceled`
* `paymentLibraryExit`

I would review the documentation and sample included in the zip file. However, I would also very strongly recommend that you investigate whether other products meet your needs. You can find some related discussion and alternative products at https://github.com/paypal/PayPal-REST-API-issues/issues/2 .

**Comment by kuldeep13990** [comment]
@bluk  i implemented all delegates.

**Comment by bluk** [comment]
By the time that you are adding your button, has the library been initialized? I'm wondering if you called `[PayPal getPayPalInst]` do you get nil back or is it the button call itself?

**Comment by kuldeep13990** [comment]
i just forgot to initialise PayPal with ID and Environment.

now you can close the question.
