### ISSUE TITLE
How to Verify the PayPal Email ID?

### ISSUE THREAD

**Issue by kuldeep13990** [paypal/sdk-packages#109]
I want to check wether user entered PayPal email is valid or not.

and for that i used below url.

https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize?client_id=MY-CLIENT-ID&response_type=code&scope=openid+email+address+phone&redirect_uri="MY REDIRECT URI"

I also add my URI in PayPal App Redirect URI but i get below error.

**Relying Party Validation error: scope in the request does not match any of the registered clients. Please check the request.**

How can i fix that?

**Comment by xiaoleih41** [comment]
This is a duplicate ticket. Please check updates on https://github.com/paypal/sdk-packages/issues/109.

**Comment by kuldeep13990** [comment]
@xiaoleih41 , where you found duplicate ticket?

on #109 it redirect to my question.

**Comment by xiaoleih41** [comment]
I quoted wrong ticket.  it should be https://github.com/paypal/sdk-packages/issues/110 and https://github.com/paypal/PayPal-iOS-SDK/issues/521. Please let me know if need any further assistance.

**Comment by pp-randy** [comment]
This is resolved here: https://github.com/paypal/PayPal-iOS-SDK/issues/521
