### ISSUE TITLE
Does Payflow_dotNET.dll deprecated

### ISSUE THREAD

**Issue by vkhangyang** [paypal/sdk-packages#111]
### General information

* SDK/Library version: Payflow_dotNET.dll
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

I'm upgrading legacy system that used Payflow_dotNET.dll for Paypal Pro to DotNet Core. 
Does Payflow_dotNET.dll deprecated? If yes, which one is covering its function?
Is Payflow_dotNET.dll opensource or not?

**Comment by pp-randy** [comment]
It is not open source at this time.  We are working on getting the source moved to GitHub.  You can email DL-PP-Payflow-SDK@paypal.com in the mean time and request a more updated copy. 

I'm not sure what changes would be needed to support DotNet Core.  Payflow has a named-value pair (NVP) API if you want to sent http requests to it directly https://developer.paypal.com/docs/classic/payflow/integration-guide/#sending-a-simple-transaction-to-the-server.
