### ISSUE TITLE
"System is unavailable. Please try again." error

### ISSUE THREAD

**Issue by sanjinl** [paypal/sdk-packages#112]
I'm getting the "System is unavailable. Please try again." issue after trying PayPalMPL integration using PhoneGap (Cordova) for the first time this past weekend. 

I get to the checkout workflow in a Sandbox environment where I'm being asked for username/password or a phone/pin. No matter what I type in, when I click OK or Review I get "System unavailable. Please try again later." error. The same happens if I try to use the Live environment as well.

I'm using Android MPL version 1.5.6.58 with a payment of £1 to a single receiver using PaymentType.TYPE_GOODS.

**Comment by trainerbill** [comment]
@sanjinl  MPL is super old and I am not even sure if it is still supported.  Since you are using cordova, I think you would be able to integrate with our checkout javascript library:

https://github.com/paypal/paypal-checkout

Otherwise you can use webviews to navigate to paypal.com once you have a token.

**Comment by mitesh-sardhara** [comment]
@trainerbill I am also facing same issue while using PayPal MPL lib on Android native app.. Please suggest me the Solution for Android Native. Thanks.

**Comment by mitesh-sardhara** [comment]
On Lenovo K4 Note it's working, but not working for Samsung S8

**Comment by trainerbill** [comment]
@mitesh-sardhara We only have native SDKs for Braintree at this time.

https://github.com/braintree/braintree_android

If you only want PayPal and don't want to go over Braintree then you can use Chrome Custom Tabs to open a new browser in app and redirect to the /checkoutnow URL with a token.

**Comment by mitesh-sardhara** [comment]
@trainerbill Thank you for the prompt respond. I appreciate it. 
So, Do you have any reference link/ tutorial or example for integrating PayPal with Chrome Custom Tabs on android...? So, II can check and integrate.

**Comment by trainerbill** [comment]
@mitesh-sardhara I don't have any examples for custom tabs unfortunately.  This would be the process.

1.  Get your payment token via setexpresscheckout or REST payment create.  make sure the returnurl parameter is an application link in your native app.  myapp://paypal/done
2.  Launch a custom tab and go to the /checkoutnow?token=TOKENFROMABOVE
3.  When user completes the flow we will redirect to myapp://paypal/done and your app should close the custom tab.

**Comment by xiaoleih41** [comment]
Close the thread due to inactivity. Please resubmit if the issue is not solved.
