### ISSUE TITLE
Payflow Gateway dotNET SDK support for TLS1.2

### ISSUE THREAD

**Issue by bonduni-nathang** [paypal/sdk-packages#113]
### General information

* SDK/Library version: payflow-gateway/dotnet
* Language, language version, and OS: dotNET, C#

### Issue description
Will there be an update to the Payflow_dotNET SDK to support versions of the dotNET Framework greater than v4.5? I am looking to update our web applications to support TLS1.2 and HTTP/1.1. 

Payflow_dotNET_v4.50RC.zip still seems to be running on dotNET Framework 2.0.

**Comment by xiaoleih41** [comment]
Please email DL-PP-Payflow-SDK@paypal.com  for the updated version status.

**Comment by xiaoleih41** [comment]
Close this thread as a solution has been provided.
