### ISSUE TITLE
Unable to find Frequency option used with when using PAYPERIOD AS DAYS in Recurring billing.

### ISSUE THREAD

**Issue by iDarshn** [paypal/sdk-packages#118]
### General information

* SDK/Library version: 4.4.0.0
* Environment: .Net C#

### Issue description

=>I am not able to find **Frequency** option using ,NET SDK with above described version.
=>In API Doc they have stated that we need to set frequency if we have user **Days** as **PayPeriod**. 

==> Is this an issue or am I missing something ?

Stuck with this thing. Please help asap.

Thanks.

**Comment by bluk** [comment]
Please contact [PayPal Technical Support](https://developer.paypal.com/support/) for help with this issue.
