### ISSUE TITLE
Error when initial PalPalMPL iOS

### ISSUE THREAD

**Issue by mrgaolei** [paypal/sdk-packages#43]
When I call `[PayPal initializeWithAppID:PAYPAL_APP_ID forEnvironment:ENV_LIVE];`
The console prompt:
```
2014-12-02 10:11:19.150 M6Test[24059:2380924] Checking Error********************
2014-12-02 10:11:19.150 M6Test[24059:2380924] Posting Error: -1
```

I print `[PayPal getPayPalInst].responseMessage`:
```
    category = Application;
    errorId = 500;
    message = "internal server error";
    severity = Error;
```

**Comment by neilco** [comment]
I'm seeing this too. The only difference being I'm using the sandbox environment.

**Comment by romk1n** [comment]
@mrgaolei please see @neilco reply. Thanks @neilco
