### ISSUE TITLE
libPayPalMPL.a, missing required architecture arm64

### ISSUE THREAD

**Issue by disequilibrio** [paypal/sdk-packages#44]
While waiting for the third party payments support in the new iOS SDK, is it possible to provide a new version of this SDK that would be compliant with arm64? Thanks.

**Comment by romk1n** [comment]
@disequilibrio the 64 bit support has been introduced since version 2.1.2, please use latest [2.1.5](https://github.com/paypal/sdk-packages/blob/gh-pages/MPL/PayPalMPL_2-1-5_iPhone_DevelopersPackage.zip)

**Comment by disequilibrio** [comment]
Hi, 
thanks for your reply.
Unfortunately, using the latest version, I’m still getting this error:

libPayPalMPL.a, missing required architecture arm64

**Comment by romk1n** [comment]
@disequilibrio have you included all the libraries required for linking ? Perhaps this issue may help https://github.com/paypal/sdk-packages/issues/27

**Comment by disequilibrio** [comment]
Ok, that really did help.
Thank you very much indeed.
