### ISSUE TITLE
armv7s support in v2.1.5?

### ISSUE THREAD

**Issue by sergey-yakimov** [paypal/sdk-packages#45]
Hello,

for version 2.1.5 there is no armv7s?

lipo -info libPayPalMPL.a 
Architectures in the fat file: libPayPalMPL.a are: armv7 i386 x86_64 arm64

Same issue as https://github.com/paypal/sdk-packages/issues/27 - there was mentioned that in version 2.1.2 there is support for armv7s (https://github.com/paypal/sdk-packages/issues/27#issuecomment-39703305).

**Comment by romk1n** [comment]
@sergey-yakimov fixed in 2.1.6, but please use [2.1.7](https://github.com/paypal/sdk-packages/commit/40d0923b24a3a56529c89bab9745eeeed55287e5) release
