### ISSUE TITLE
Transaction details 

### ISSUE THREAD

**Issue by SagarRaiyani** [paypal/sdk-packages#46]
Hello

I have including MPL library in our project,  but the MPL return a PAY_KEY after payment successful  in result so how to get transaction id through PAY_KEY, please give me suggestion.

**Comment by mattjacunski** [comment]
@SagarRaiyani - How this is done will depend on which mobile platform you are targeting.  See links to documentation at the bottom of https://developer.paypal.com/webapps/developer/docs/classic/mobile/gs_MPL/.
