### ISSUE TITLE
iOS MPL library 2.1.6: checkoutWithPayment window still overflows screen on iPhone 6

### ISSUE THREAD

**Issue by zanetalb** [paypal/sdk-packages#47]
When calling [[PayPal getPayPalInst] checkoutWithPayment:payment], the window that MPL opens overflows screen on iPhone 6 and 6 plus as well.

**Comment by romk1n** [comment]
@zanetalb can you please send a screenshot ? is the same issue persists with earlier version ?

**Comment by zanetalb** [comment]
Yes, it's the same issue with 2.1.4. Fixed in 2.1.5 but reappeared in 2.1.6
![img_8098](https://cloud.githubusercontent.com/assets/11209334/6409755/f7bc6fac-be67-11e4-88dc-2634ae4e967f.PNG)

**Comment by romk1n** [comment]
@zanetalb thank you very much for bringing this to our attention. [2.1.7](https://github.com/paypal/sdk-packages/commit/40d0923b24a3a56529c89bab9745eeeed55287e5) release should have this fix.
