### ISSUE TITLE
Adding Credit Card Payment Option

### ISSUE THREAD

**Issue by KVidhyanand** [paypal/sdk-packages#49]
MPL supports parallel payment. Payment is distributed to multiple receivers from Single Buyer. But As PayPal-IOS-SDK having Credit Card Option for payment with Credit Card Scan.(Single Mode of Payment).

https://github.com/paypal/PayPal-iOS-SDK
https://developer.paypal.com/docs/integration/mobile/mobile-sdk-overview/

In above URL's we find SDK with Credit Card Scan, and Credit Card Payment Options also..!

![ios simulator screen shot may 5 2015 11 46 10 am](https://cloud.githubusercontent.com/assets/5211867/7468088/c21c306e-f321-11e4-972d-96f01bc67d36.jpg)

Its better to have Credit Card Payment Option to MPL also.

**Comment by romk1n** [comment]
@KVidhyanand Unfortunately we are not making any changes to MPL beyond critical bug fixes. PayPal-iOS-SDK is based on the new PayPal REST APIs which has credit card support. MPL is based on Adaptive Payments APIs.
