### ISSUE TITLE
MPL annoys with Timeout alerts

### ISSUE THREAD

**Issue by tapwork** [paypal/sdk-packages#52]
It pops up with `UIAlertView`
How can I avoid those?
It's ok for debug but not acceptable in the release app
![screen shot 2015-06-22 at 22 02 43](https://cloud.githubusercontent.com/assets/397342/8291871/69c2f3fe-192c-11e5-8016-cf03e7c15c61.png)
![screen shot 2015-06-22 at 21 41 33](https://cloud.githubusercontent.com/assets/397342/8291875/6c0cd0d0-192c-11e5-96a7-3d38a46c4c72.png)

**Comment by tapwork** [comment]
Ok I found a nasty workaround to disable the Alerts by swizzling
```objc
#import <objc/runtime.h>

@implementation UIAlertView (Disable)

+ (void)load
{
    Method original;
    Method mock;
    original = class_getInstanceMethod(self, @selector(show));
    mock = class_getInstanceMethod(self, @selector(tcl_disable_show));
    method_exchangeImplementations(mock, original);
}

- (void)tcl_disable_show
{
    // do nothing for PayPal
    if (![[self.delegate class] isSubclassOfClass:NSClassFromString(@"PPUtils")]) {
        [self tcl_disable_show];
    }
}

@end
```

**Comment by tomwhipple** [comment]
We are only making critical updates to MPL at this time. Unfortunately this doesn't meet that bar.
