### ISSUE TITLE
Fix Your Podspecs Please!

### ISSUE THREAD

**Issue by jacktator** [paypal/sdk-packages#63]
Current Pod for MPL is broken, Please refer to [this issue](https://github.com/CocoaPods/Specs/pull/13830#issuecomment-193233449).

**Comment by bluk** [comment]
I am working on getting the pod ownership transferred to me, and will try to publish a new version of the Podspec as soon as possible.

**Comment by bluk** [comment]
Just FYI, I filed another dispute with CocoaPods to reclaim ownership today.

**Comment by bluk** [comment]
I've pushed [version `2.1.7`](https://github.com/CocoaPods/Specs/blob/master/Specs/PayPalMPL/2.1.7/PayPalMPL.podspec.json) to the repository. I also used the CocoaPods `vendored_libraries` config and a few other changes which should help with recent Xcode 6.x+ project settings. Please leave a comment or create a new issue if this doesn't work for you.

Thanks for your patience.
