### ISSUE TITLE
iOS MPL 2.1.7, Cannot open PreApproval window

### ISSUE THREAD

**Issue by jacktator** [paypal/sdk-packages#64]
According to [Docs](https://www.paypalobjects.com/webstatic/en_US/developer/docs/pdf/pp_mpl_developer_guide_and_reference_iphone.pdf), when calling the following code, SDK should open the PreApproval window, however it is not working in our case. Here's a code snip in Swift.

                        //preApprovalKey = keyFromServer, "PA-xxxxxxxxxxxxxxxxx"
                        let paypal = PayPal();
                        paypal.preapprovalWithKey(preApprovalKey, andMerchantName: "");

OS X 10.10.5, XCode 7.2.1, Swift 2.0, iOS9.2, Tested Simulator arm64 & real device.

When the above lines are excuted, nothing happens, no window, no crash, no log, no error, nothing. Any idea why it might happen?

PS: No, Chained payment is a requirement, so iOS-SDK is not an option
PS 2: We've been experiencing "Error: Service not available" during initialization in the past few days, but it seems to be fixed now. 
PS 3: It's in Sandbox environment, correct id, correct environment.
PS 3: A [similar issue](http://stackoverflow.com/questions/34915835/paypal-mpl-version-2-1-7-in-ios-has-stopped-working-since-20th-jan-2016-is-it) by someone else can be found at stackoverflow.

Any help is much, MUCH appreciated.

**Comment by CGTGauravk** [comment]
Hi Jack, this is the "someone" here who posted that question on stackoverflow.
Did this issue solve out for you?
For me it did, back then, but now again I am facing similar issue i.e. nothing happening at all on calling this method.
