### ISSUE TITLE
Accept payment via credit card in paypal mobile

### ISSUE THREAD

**Issue by simformsolutions** [paypal/sdk-packages#66]
We are using paypal MPL for payment in mobile. but once make payment in paypal. they are allow user to pay via creditcard they only allow only via paypal account. 
can you please guide me how do I resolve this.

thanks in advance

**Comment by pp-randy** [comment]
Previous thread for Credit Cards in MPL https://github.com/paypal/sdk-packages/issues/49

@simformsolutions we have mobile solutions if you require credit cards payments documented here: https://developer.paypal.com/docs/integration/mobile/mobile-sdk-overview/
