### ISSUE TITLE
Split payment using paypal

### ISSUE THREAD

**Issue by simformsolutions** [paypal/sdk-packages#67]
My Requirement,
In application we have feature to purchase ticket from app, so once user checkout using paypal we need to split amount and send to ticket owner and app owner.
i.e. $10 ticket price
send $8 to ticket provider and $2 to App owner.

can you please guide us how do we achieve this feature.
thanks in advance

**Comment by pp-randy** [comment]
You have a few options.  If you want to show the payer both receiving parties then you would want a parallel payment.  If you want to show only the ticket provider getting $10 then send $2 to the app owner then a chained payment would be another option.

Express Checkout support Parallel Payments: 
https://developer.paypal.com/docs/classic/express-checkout/ht_ec-parallelPayments/

Adaptive Payments supports Parallel and Chained Payments:
https://developer.paypal.com/docs/classic/api/adaptive-payments/Pay_API_Operation/
