### ISSUE TITLE
iOS MPL 2.1.7, Suddenly giving 'This app not using a supported version of the PayPal library.' error. 

### ISSUE THREAD

**Issue by jacktator** [paypal/sdk-packages#68]
Using checkoutWIthAdvancedPayment method

It's all working fine, until last night.

        PayPal.initializeWithAppID(PAYPAL_SANDBOX_APP_ID, forEnvironment: ENV_SANDBOX);

Now, whenever I'm trying to initialize PayPal, 

2016-04-05 11:31:01.545 Tipper[70913:4554432] Checking Error********************
2016-04-05 11:31:01.545 Tipper[70913:4554432] Posting Error: 2147483647
2016-04-05 11:31:01.545 Tipper[70913:4554432] DEVELOPER ERROR: This app not using a supported version of the PayPal library.

Any idea?

**Comment by bluk** [comment]
@jacktator Are you still experiencing this issue? I tried a sample app on sandbox and did not encounter this error.

**Comment by jacktator** [comment]
@bluk Thank you for your reply. 

I've tried running the demo app on XCode 7.3, it crashes upon launch

Here's the stack trace

2016-04-05 10:11:42.850 InteractiveDemo[69446:4438450] *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3512.60.7/UIApplication.m:3401
2016-04-05 10:11:42.856 InteractiveDemo[69446:4438450] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'
*** First throw call stack:
(
	0   CoreFoundation                      0x02c5e494 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x02718e02 objc_exception_throw + 50
	2   CoreFoundation                      0x02c5e32a +[NSException raise:format:arguments:] + 138
	3   Foundation                          0x006a5322 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 118
	4   UIKit                               0x00a4d6dd -[UIApplication _runWithMainScene:transitionContext:completion:] + 4008
	5   UIKit                               0x00a72b2c __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke3246 + 68
	6   UIKit                               0x00a49b8a -[UIApplication workspaceDidEndTransaction:] + 163
	7   FrontBoardServices                  0x041d2110 __37-[FBSWorkspace clientEndTransaction:]_block_invoke_2 + 71
	8   FrontBoardServices                  0x041d1be7 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 54
	9   FrontBoardServices                  0x041ef27f __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 23
	10  FrontBoardServices                  0x041ef0ab -[FBSSerialQueue _performNext] + 174
	11  FrontBoardServices                  0x041ef4fa -[FBSSerialQueue _performNextFromRunLoopSource] + 52
	12  FrontBoardServices                  0x041ee7e8 FBSSerialQueueRunLoopSourceHandler + 33
	13  CoreFoundation                      0x02b70e5f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	14  CoreFoundation                      0x02b66aeb __CFRunLoopDoSources0 + 523
	15  CoreFoundation                      0x02b65f08 __CFRunLoopRun + 1032
	16  CoreFoundation                      0x02b65846 CFRunLoopRunSpecific + 470
	17  CoreFoundation                      0x02b6565b CFRunLoopRunInMode + 123
	18  UIKit                               0x00a492da -[UIApplication _run] + 540
	19  UIKit                               0x00a4eeb9 UIApplicationMain + 160
	20  InteractiveDemo                     0x000491c0 main + 128
	21  libdyld.dylib                       0x033a1a25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by jacktator** [comment]
Resolved, The build number we used was too long. Changing it to a smaller number resolved the issue. BUT, the demo app still does not run.

**Comment by bluk** [comment]
The samples were built prior to iOS 9. I'll try to update them as time permits (for the Bitcode Enabled one, you just need to disable Bitcode in the Target's Build Settings).

For the issue with the root view controller, you need to make a change like:
```
-       [window addSubview:navigationController.view];    
+       [window setRootViewController:navigationController];
```

in the *AppDelegate.

**Comment by jacktator** [comment]
@bluk Thanks for the quick reply. For SimpleDemo, I DID disable Bitcode. But I think there's a flag added somewhere in the setting that's causing the problem

**Comment by bluk** [comment]
Should be updated in https://github.com/paypal/sdk-packages/commit/a84a68787d9f3ee5f7e9041af03d62a8d91a550a
