### ISSUE TITLE
paypal new MPL lib not working in Live environment 

### ISSUE THREAD

**Issue by elluminati10** [paypal/sdk-packages#71]
getting error "login fail plaese try again " in LIVE environment
i m struck
plz help me

	PayPal pp = PayPal.getInstance();
		if (pp == null) {

			pp = PayPal.initWithAppID(this, Const.PAYPAL_CLIENT_ID,
					PayPal.ENV_LIVE);

		}

		pp.setFeesPayer(PayPal.FEEPAYER_PRIMARYRECEIVER);
		pp.setShippingEnabled(true);
		pp.setDynamicAmountCalculationEnabled(false);

**Comment by pp-randy** [comment]
Are you still seeing this issue?  I edited to remove the picture with your email address. To me this indicates invalid credentials, have you tried with a different account?

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
