### ISSUE TITLE
Paypal transaction failed .

### ISSUE THREAD

**Issue by elluminati10** [paypal/sdk-packages#77]
give this type of error "your account and limited or blocked. to solve the problem, visit the website www.paypal.it " . But my paypal account woking properly not blocked . So my application Give such type of error . I am using MPL paypal lib. Plz help me . My account connected to a PayPal prepaid card.

![1](https://cloud.githubusercontent.com/assets/15337099/16144955/d928751a-3493-11e6-85aa-581c927c6a89.png)

**Comment by pp-randy** [comment]
This issue can be better investigated by PayPal Technical Support, if it is an account issue they will be able to guide you to the proper customer support team.  You can use https://www.paypal-techsupport.com/app/ask/ or https://it.paypal-techsupport.com/app/ask/ depending on your language preference to create a ticket with them.
