### ISSUE TITLE
Adaptive payment with future payment

### ISSUE THREAD

**Issue by augustinAJ** [paypal/sdk-packages#83]
Can we combine the functionalities of Adaptive payments and Future payment in this library for iOS side ??
I want to user to link the paypal account first and agree for future payment.. Later **I should be able to send money to any other user from the linked account without user logging in each time**. Is this feature is supported ?? If so please give appropriate directions... Waits for your assistance.

**Comment by ppmtscory** [comment]
If you're integrated with Adaptive Payments (and this SDK package), then you'd need to utilize [Preapproved Payments](https://developer.paypal.com/docs/classic/adaptive-payments/ht_ap-basicPreapproval-curl-etc/).

**Comment by augustinAJ** [comment]
@ppmtscory Thankyou so much.. Was very helpful.
