### ISSUE TITLE
Install Payflow_dotNET.dll on Windows Server 2012 R2 - IIS 8.5

### ISSUE THREAD

**Issue by PrimaMusic** [paypal/sdk-packages#85]
Can someone give me step by step instructions on how to install Payflow_dotNET.dll on Windows Server 2012 R2, IIS 8.5.  I have tried downloading the current SDK/dll and registering it using regasm.  I have copied the dll to the /windows/assembly directory.  PayPal.Payments is present in the registry.  When I try to create an object in my .asp page, using Server.CreateObject("PayPal.Payments.Communication.PayflowNETAPI") I get the error message - Microsoft VBScript runtime error '800a01ad' ActiveX component can't create object.  PayPal Integration Support told me to add a module using IIS8.  When I added a module for the Payflow_dotNET.dll, I get a HTTP 503 error accessing the website.  I can reverse what has been registered.  If someone can tell me the correct installation, I would appreciate it.

**Comment by pp-randy** [comment]
@PrimaMusic which Payflow folder are you pulling from? 
payflow-gateway
paypal-payments-pro-payflow-edition

When I've seen similar issues in the past its usually related to COM in a 64-bit environment and some of the steps being related to 32-bit.  Is your application pool running in 64-bit or 32-bit mode?

**Comment by PrimaMusic** [comment]
Thank you pp-randy.  The application pool setting for "Enable 32-bit Applications" is set to True.

**Comment by PrimaMusic** [comment]
@pp-randy thanks for pointing me in the right direction.  I changed the app pool to set "Enable 32-bit Applications" to false.  The PayPal.Payments.Communication object in now loading.  This has created another problem.  Other objects, like Mail Enable - Server.CreateObject("MEMail.Message") - are now failing.  I assume that it is a 32-bit application.  Any suggestions on how to get both to work?

**Comment by pp-randy** [comment]
You could try to register the Payflow dll as 32-bit; unfortunately, I'm not able to test this currently. You would use the regsvr32 that is in C:\Windows\SysWOW64 instead of System32.  I believe this is still the case for your server version and SysWOW64 is actually the 32-bit side. 

For regasm and gacutil use your 32-bit .Net framework so Microsoft.NET\Framework\ instead of Microsoft.NET\Framework64\

Again I apologize I am not 100% if you can register the Payflow DLL in 32-bit since I am experiencing issues locally.

**Comment by PrimaMusic** [comment]
I finally figured this out, along with some help from @pp-randy.  I don't know if pp-randy works for PayPal, however, aside from his help, I got absolutely no support from PayPal.  I pay them tens of thousands of dollars a year and they could not even let me talk to somebody in the technical department about this.  I left phone messages for four different people in PayPal's Executive Escalations Group.  Not one of them returned my phone call!  I have to say that PayPal is one of worst companies that I have to deal with.

In order to solve this, I could not use the current Payflow_dotNET.dll posted on the PayPal site.  Fortunately, I had an older version of the dll.  It was version 4.3.3.  I attempted to follow the regasm / gacutil process using this dll.  I tried every version of .net in Microsoft.NET/Framework & Microsoft.NET/Framework64 using the regasm located in Windows\System32.  This is the way that I have always done it.  This process worked on every version of Windows Server & IIS that I have used in the past.  This time, I was able to get the dll registered using the process above, however, it would only run if I changed the application pool to disable 32-bit applications (the default).  This is a Classic ASP app and I have other objects that are 32-bit, such as MailEnable.  When I turned 32-bit on in the app pool, the PayPal object would crash the app pool and give a HTTP 503 error.  Finally, I tried to register the dll using the regasm in Windows/SysWOW32, instead of Windows/System32.  It worked.  This registered the dll as 32-bit.  This is not documented anywhere at PayPal - mostly because they couldn't care less whether their customer's credit card processing works or not.  I hope this helps someone in the future.

**Comment by pp-randy** [comment]
@PrimaMusic I am glad you were able to resolve your integration issue.  

I do work for PayPal.  I apologize we did not have the documentation to support your integration readily available and for any downtime or inconvenience this has caused.  I will follow up further in regards to the documentation.

Regarding the support you received. I'm not sure if you reached out to PayPal Technical Support directly, if not, they can be reached by web form here: https://www.paypal-techsupport.com/app/ask.  If you did, please respond with your reference number and I will follow up.

**Comment by PrimaMusic** [comment]
@pp-randy Thanks again for following up.   I did submit a request to PayPal Technical Support.  The reference number is 160801-000333.  They responded by asking where I get the dll and telling me that Windows Server 2012 doesn't support 32-bit anymore - which is incorrect.  I used to be you could actually talk to someone in technical support and they would help you over the phone.  Now, the only way to get help is to make a post in a forum.  When you have a multi-million dollars eCommerce business and your shopping cart will not work, making a post in a forum is hardly an acceptable way to receive support from one of your mission critical suppliers.   I am not blaming you, I am just very frustrated with the way this was handled.  BTW, I was allowed to talk to the Integration Support department.  Here is an excerpt from an email they sent me, "I understand your frustration and we are very glad that you choose us to process your payments. However, the departments involved are not departments that work from or on the phones.  The way to contact them is via the GIT account.   Should that avenue not be acceptable you can certainly look into external development resources that are familiar with the IIS server architecture that could help resolve the .DLL issues you are experiencing.   Here is a list of PayPal certified developers should that be something that interests you..."

**Comment by pp-randy** [comment]
Thank you for the information.  Something to note from the support ticket; although, 32-bit will work with Windows Server 2012 it does note this being deprecated https://technet.microsoft.com/en-us/library/hh831568(v=ws.11).aspx.  So Windows Server 2016 will most likely not support 32-bit dll files.
