### ISSUE TITLE
iOS, Internal server error when try to initialise SDK

### ISSUE THREAD

**Issue by RajathShetty-above** [paypal/sdk-packages#90]
This method always fails, when I initialise this SDK. 
PayPal.initialize(withAppID: "APP-****************", for: ENV_SANDBOX)

This method will display an alert, "Internal server error”. In console it will print “Posting Error: -1”.

App configuration,

Version : iOS 9.0
Language : Swift 3
Xcode: 8.0

**Comment by pp-randy** [comment]
For sandbox you should be using APP-80W284485P519543T.  Can you check if this is correct?  If it is, can you provide a correlation id from the API response?

**Comment by RajathShetty-above** [comment]
Thanks you for the response. Yes, I am passing same app ID,
PayPal.initialize(withAppID: "APP-80W284485P519543T", for: ENV_SANDBOX)

This will fails and alert will be shown as "internal server error".  In console I can see,

Checking Error********************
Posting Error: -1

After that, if i call, payPal.advancedCheckout(with: payment) it won't do anything. No delegate methods get called.

**Comment by RajathShetty-above** [comment]
I missed to add "Bundle display name", this resolved issue. Thanks.
