### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by abogab** [paypal/sdk-packages#96]
Similar to >>An unexpected error has occurred #81<< posted by @juanmartincontreras, we can not login to PayPal using PayPal_MPL_1.5.6.58.

We have noticed that if we only use a password with aphanumeric characters, the problem go out, but if in the password a character like '&' or ')' is included, the problem persist.

I hope you can help us. 

Thanks!.

**Comment by abogab** [comment]
The log not says to much but here it is:

11-01 01:16:07.611 20663-20663/com.fco.apptest V/ActivityThread: updateVisibility : ActivityRecord{269285f0 token=android.os.BinderProxy@aebee48 {com.fco.apptest/com.fco.apptest.ActivitySelect}} show : true
11-01 01:16:07.636 20663-20724/com.fco.apptest D/mali_winsys: new_window_surface returns 0x3000,  [540x960]-format:1
11-01 01:16:07.651 20663-20724/com.fco.apptest D/mali_winsys: new_window_surface returns 0x3000,  [540x960]-format:1
11-01 01:16:07.746 20663-20663/com.fco.apptest I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@202910cb time:85572113
11-01 01:16:08.396 20663-20663/com.fco.apptest D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
11-01 01:16:18.196 20663-20663/com.fco.apptest D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
11-01 01:16:31.351 20663-20663/com.fco.apptest D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
11-01 01:16:32.316 20663-20663/com.fco.apptest D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
11-01 01:16:35.491 20663-20736/com.fco.apptest I/System.out: Thread-12904(ApacheHTTPLog):isSBSettingEnabled false
11-01 01:16:35.491 20663-20736/com.fco.apptest I/System.out: Thread-12904(ApacheHTTPLog):isShipBuild true
11-01 01:16:35.491 20663-20736/com.fco.apptest I/System.out: Thread-12904(ApacheHTTPLog):SMARTBONDING_ENABLED is false
11-01 01:16:35.491 20663-20736/com.fco.apptest I/System.out: Thread-12904(ApacheHTTPLog):SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
11-01 01:16:35.491 20663-20737/com.fco.apptest I/System.out: Thread-12905(ApacheHTTPLog):isSBSettingEnabled false
11-01 01:16:35.491 20663-20737/com.fco.apptest I/System.out: Thread-12905(ApacheHTTPLog):isShipBuild true
11-01 01:16:35.491 20663-20737/com.fco.apptest I/System.out: Thread-12905(ApacheHTTPLog):SMARTBONDING_ENABLED is false
11-01 01:16:35.491 20663-20737/com.fco.apptest I/System.out: Thread-12905(ApacheHTTPLog):SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
11-01 01:16:35.956 20663-20737/com.fco.apptest I/System.out: Thread-12905 calls detatch()

**Comment by abogab** [comment]
And just appear this:
![device-2016-11-01-012029](https://cloud.githubusercontent.com/assets/23184793/19882267/fabdde8c-9fd1-11e6-994f-73429633f381.png)

**Comment by pp-randy** [comment]
The MPL uses Adaptive Payments, which are currently a limited release. 

Have you reviewed the alternatives to the MPL? 
https://developer.paypal.com/docs/integration/mobile/mobile-sdk-overview/
