### ISSUE TITLE
Paypal MPL initialise failed in iOS

### ISSUE THREAD

**Issue by klkiat** [paypal/sdk-packages#98]
Here is the error log message i received when i tried to initial paypal MPL with 
`[PayPal initializeWithAppID:PAYPAL_MPL_SANDBOX_APP_ID forEnvironment:ENV_SANDBOX];`

`nw_endpoint_handler_add_write_request [2.1 173.0.82.101:443 failed socket-flow (satisfied)] cannot accept write requests
2016-12-29 11:35:50.243875 Apps[820:410064] [] __tcp_connection_write_eof_block_invoke Write close callback received error: [22] Invalid argument
2016-12-29 11:35:50.266581 Apps[820:410032] Checking Error********************
2016-12-29 11:35:50.266818 Apps[820:410032] Posting Error: -1
2016-12-29 11:35:50.413278 Apps[820:410032] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-12-29 11:35:50.414171 Apps[820:410032] [MC] Reading from public effective user settings.`

In live environment are no problem but switch to sandbox will hit this error, any solution to this ?

Thanks you

**Comment by klkiat** [comment]
Hi, today i still facing the same error due to MPL initialise failed and payment can't make.
Anyone looking at this error ? Please reply if you able to help, thanks you

**Comment by zorovu** [comment]
Hi @klkiat 
I'm getting the same problem with you. 
Waiting the feedback from PayPal.

**Comment by kittu4ios** [comment]
Hi I am also facing same problem. please help me to fix this issue.thanks in advance.

**Comment by bluk** [comment]
Sorry for the delay in response. Is everyone facing this issue in sandbox or live? Is this problem intermittent or constant (e.g. if you force quit your app and restarted, does it work)? Also, can you give more details about your environment such as what version of Xcode and if you're trying this on a device and/or simulator? I want to make sure that the errors are the same one.

In the sandbox environment, I did encounter a "System is unavailable", but I was able to make a simple payment, parallel payment, and chained payment after retrying. I've opened internal issue PPPLMER-25614 to track down the "System is unavailable" error.

**Comment by hovuki** [comment]
Have the same error been hit since last 2 weeks.
Here is the detail of the error:
- Facing this issue every time when initial MPL library in startup with sandbox environment
- Quit and restarted the apps do not help to solve this issue
- Xcode version 8.2 with iOS deployment target 8.0 and 9.0
- Tested in simulator and device hit the same issue

"System is unavailable" alert warning come out and disabled the payment button, in "getPayPalMPLInitializationStatus" function status are returned error.

**Comment by bluk** [comment]
The `System is unavailable. Please try again later.` should be resolved. If you still encounter the issue, please leave a comment. Thanks for your patience.
