### ISSUE TITLE
Paypal MPL library failed to load in Android

### ISSUE THREAD

**Issue by okvaishakh21** [paypal/sdk-packages#99]
I am using PayPal_MPL_1.5.6.58 in my application under sandbox environment. My app was working fine till December 2016. Now the Paypal checkout button is not loading. I am using pre-approved adaptive payment using MPL library in my app.

**Comment by pepito87** [comment]
I'm running PayPal_MPL_1.5.6.56 and my button seems to load but when you tap on it, it brings up a failure code. The message comes up as "we're sorry, there was a problem completing your payment". Also this has been working before. 

I wonder if it's a similar issue to what your having @okvaishakh21

**Comment by okvaishakh21** [comment]
@pepito87  in my android app the button is not even showing. For my iOS app i can see the PayPal button but it is in disabled state. I couldn't make any clicks with that button

**Comment by bluk** [comment]
Sorry for the delay in response. Are these issues happening only in the sandbox environment? Also, are they consistent or intermittent? What Android API are you targeting? Is there anything else in a console log that might be related to the issue?

We have an internal issue PPPLMER-25614 to track down some server side intermittent issues with payment initialization for MPL, but I want to ensure these are the same problem.

**Comment by okvaishakh21** [comment]
@bluk this is happening in sandbox environment. target api for android is 23. My iOS app also facing the same problem, the paypal button is in a disabled state

**Comment by bluk** [comment]
The `System is unavailable. Please try again later.` should be resolved. If you still encounter the issue, please leave a comment. Thanks for your patience.

**Comment by Skytile** [comment]
@bluk I'm just implementing now, so I can't be sure whether it's an issue with my implementation or if it's on the server side, but I'm still getting the referenced error message. On Android in both Sandbox and Live environments, I get `System is unavailable. Please try again later.` This is using version `PayPal_MPL_1.5.6.58`. I check the result Intent for an error code onActivityResult, and it seems there isn't one.

**Comment by bluk** [comment]
@Skytile I was able to run a simple payment test transaction in sandbox using the Demo app included in the iOS development package a minute ago. (I did change the code for the receiver of the payments to a sandbox account that I have). If you are going to use iOS as well, it might be useful to see if that Demo app can run and see how payments are setup.

For the Android case, is there any other system messages that were printed in the logs? If you can create a new issue with any additional logs and/or a sample of the code you're using, that would be helpful.

(Note if this is a new integration, I would advise checking to see if other PayPal / Braintree products can fit your needs. The Mobile Payments Library's API is in [limited release](https://github.com/paypal/sdk-packages/tree/gh-pages/MPL).)

**Comment by ganeshank** [comment]
I am getting the same error for android (Sandbox). I took the latest jar from https://github.com/paypal/sdk-packages/tree/gh-pages/MPL, but still getting it same error. Please help me.

**Comment by xiaoleih41** [comment]
@ganeshank This SDK has been deprecated. Have you been approved for live production? If not, please  check the PayPal/Braintree products that fits your need.
